include: package:flutter_lints/flutter.yaml


formatter:
  trailing_commas: preserve

linter:
  rules:

    # Enforce immutability and const usage
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # Disallow unwanted prints and redundant argument values
    avoid_print: true
    avoid_redundant_argument_values: true

    # Encourage proper annotations and final usage
    annotate_overrides: true
    prefer_final_locals: true

    # Enforce best practices in control flow
    curly_braces_in_flow_control_structures: true
    avoid_empty_else: true
    prefer_if_null_operators: true

    # Additional rules to enforce explicit types
    always_declare_return_types: true
    # always_specify_types: true
    require_trailing_commas: true
    use_super_parameters: true
    unnecessary_this: true
    avoid_unnecessary_containers: true
    sort_child_properties_last: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
